//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace DIXON.ReportDataSet {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ASNWifiAPSAP_Report")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class ASNWifiAPSAP_Report : global::System.Data.DataSet {
        
        private ASNWifiAPReportDataTable tableASNWifiAPReport;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public ASNWifiAPSAP_Report() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected ASNWifiAPSAP_Report(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["ASNWifiAPReport"] != null)) {
                    base.Tables.Add(new ASNWifiAPReportDataTable(ds.Tables["ASNWifiAPReport"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ASNWifiAPReportDataTable ASNWifiAPReport {
            get {
                return this.tableASNWifiAPReport;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            ASNWifiAPSAP_Report cln = ((ASNWifiAPSAP_Report)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["ASNWifiAPReport"] != null)) {
                    base.Tables.Add(new ASNWifiAPReportDataTable(ds.Tables["ASNWifiAPReport"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableASNWifiAPReport = ((ASNWifiAPReportDataTable)(base.Tables["ASNWifiAPReport"]));
            if ((initTable == true)) {
                if ((this.tableASNWifiAPReport != null)) {
                    this.tableASNWifiAPReport.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void InitClass() {
            this.DataSetName = "ASNWifiAPSAP_Report";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ASNWifiAPSAP_Report.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableASNWifiAPReport = new ASNWifiAPReportDataTable();
            base.Tables.Add(this.tableASNWifiAPReport);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private bool ShouldSerializeASNWifiAPReport() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ASNWifiAPSAP_Report ds = new ASNWifiAPSAP_Report();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public delegate void ASNWifiAPReportRowChangeEventHandler(object sender, ASNWifiAPReportRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class ASNWifiAPReportDataTable : global::System.Data.TypedTableBase<ASNWifiAPReportRow> {
            
            private global::System.Data.DataColumn columnPurchasing_Document_Number;
            
            private global::System.Data.DataColumn columnEAN_Code_of_Device;
            
            private global::System.Data.DataColumn columnSerial_Number;
            
            private global::System.Data.DataColumn columnPallet_Number;
            
            private global::System.Data.DataColumn columnMaster_Shipper_Number;
            
            private global::System.Data.DataColumn columnVendor_Lot_Number;
            
            private global::System.Data.DataColumn columnInvoice_Number;
            
            private global::System.Data.DataColumn columnMonth_of_Manufacturing;
            
            private global::System.Data.DataColumn columnInvoice_Date;
            
            private global::System.Data.DataColumn columnWarranty_in_Days;
            
            private global::System.Data.DataColumn columnPhysical_Device_Model;
            
            private global::System.Data.DataColumn columnPhysical_Device_Type;
            
            private global::System.Data.DataColumn columnPhysical_Device_Vendor;
            
            private global::System.Data.DataColumn columnDevice_IMEI_number;
            
            private global::System.Data.DataColumn columnOUI;
            
            private global::System.Data.DataColumn columnSoftware_Version;
            
            private global::System.Data.DataColumn columnPre_Password;
            
            private global::System.Data.DataColumn columnDevice_Status;
            
            private global::System.Data.DataColumn columnLogical_Function_Type;
            
            private global::System.Data.DataColumn columnDevice_Component;
            
            private global::System.Data.DataColumn columnBase_MAC_ID;
            
            private global::System.Data.DataColumn columnGlobal_SSID1;
            
            private global::System.Data.DataColumn columnGlobal_SSID2;
            
            private global::System.Data.DataColumn columnWPA_PSKSSID_PWD;
            
            private global::System.Data.DataColumn columnGPON_ID;
            
            private global::System.Data.DataColumn columnAction_for_Granite;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ASNWifiAPReportDataTable() {
                this.TableName = "ASNWifiAPReport";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal ASNWifiAPReportDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected ASNWifiAPReportDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Purchasing_Document_NumberColumn {
                get {
                    return this.columnPurchasing_Document_Number;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn EAN_Code_of_DeviceColumn {
                get {
                    return this.columnEAN_Code_of_Device;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Serial_NumberColumn {
                get {
                    return this.columnSerial_Number;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Pallet_NumberColumn {
                get {
                    return this.columnPallet_Number;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Master_Shipper_NumberColumn {
                get {
                    return this.columnMaster_Shipper_Number;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Vendor_Lot_NumberColumn {
                get {
                    return this.columnVendor_Lot_Number;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Invoice_NumberColumn {
                get {
                    return this.columnInvoice_Number;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Month_of_ManufacturingColumn {
                get {
                    return this.columnMonth_of_Manufacturing;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Invoice_DateColumn {
                get {
                    return this.columnInvoice_Date;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Warranty_in_DaysColumn {
                get {
                    return this.columnWarranty_in_Days;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Physical_Device_ModelColumn {
                get {
                    return this.columnPhysical_Device_Model;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Physical_Device_TypeColumn {
                get {
                    return this.columnPhysical_Device_Type;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Physical_Device_VendorColumn {
                get {
                    return this.columnPhysical_Device_Vendor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Device_IMEI_numberColumn {
                get {
                    return this.columnDevice_IMEI_number;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn OUIColumn {
                get {
                    return this.columnOUI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Software_VersionColumn {
                get {
                    return this.columnSoftware_Version;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Pre_PasswordColumn {
                get {
                    return this.columnPre_Password;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Device_StatusColumn {
                get {
                    return this.columnDevice_Status;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Logical_Function_TypeColumn {
                get {
                    return this.columnLogical_Function_Type;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Device_ComponentColumn {
                get {
                    return this.columnDevice_Component;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Base_MAC_IDColumn {
                get {
                    return this.columnBase_MAC_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Global_SSID1Column {
                get {
                    return this.columnGlobal_SSID1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Global_SSID2Column {
                get {
                    return this.columnGlobal_SSID2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn WPA_PSKSSID_PWDColumn {
                get {
                    return this.columnWPA_PSKSSID_PWD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn GPON_IDColumn {
                get {
                    return this.columnGPON_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Action_for_GraniteColumn {
                get {
                    return this.columnAction_for_Granite;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ASNWifiAPReportRow this[int index] {
                get {
                    return ((ASNWifiAPReportRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event ASNWifiAPReportRowChangeEventHandler ASNWifiAPReportRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event ASNWifiAPReportRowChangeEventHandler ASNWifiAPReportRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event ASNWifiAPReportRowChangeEventHandler ASNWifiAPReportRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event ASNWifiAPReportRowChangeEventHandler ASNWifiAPReportRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void AddASNWifiAPReportRow(ASNWifiAPReportRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ASNWifiAPReportRow AddASNWifiAPReportRow(
                        string Purchasing_Document_Number, 
                        string EAN_Code_of_Device, 
                        string Serial_Number, 
                        string Pallet_Number, 
                        string Master_Shipper_Number, 
                        string Vendor_Lot_Number, 
                        string Invoice_Number, 
                        string Month_of_Manufacturing, 
                        string Invoice_Date, 
                        string Warranty_in_Days, 
                        string Physical_Device_Model, 
                        string Physical_Device_Type, 
                        string Physical_Device_Vendor, 
                        string Device_IMEI_number, 
                        string OUI, 
                        string Software_Version, 
                        string Pre_Password, 
                        string Device_Status, 
                        string Logical_Function_Type, 
                        string Device_Component, 
                        string Base_MAC_ID, 
                        string Global_SSID1, 
                        string Global_SSID2, 
                        string WPA_PSKSSID_PWD, 
                        string GPON_ID, 
                        string Action_for_Granite) {
                ASNWifiAPReportRow rowASNWifiAPReportRow = ((ASNWifiAPReportRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Purchasing_Document_Number,
                        EAN_Code_of_Device,
                        Serial_Number,
                        Pallet_Number,
                        Master_Shipper_Number,
                        Vendor_Lot_Number,
                        Invoice_Number,
                        Month_of_Manufacturing,
                        Invoice_Date,
                        Warranty_in_Days,
                        Physical_Device_Model,
                        Physical_Device_Type,
                        Physical_Device_Vendor,
                        Device_IMEI_number,
                        OUI,
                        Software_Version,
                        Pre_Password,
                        Device_Status,
                        Logical_Function_Type,
                        Device_Component,
                        Base_MAC_ID,
                        Global_SSID1,
                        Global_SSID2,
                        WPA_PSKSSID_PWD,
                        GPON_ID,
                        Action_for_Granite};
                rowASNWifiAPReportRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowASNWifiAPReportRow);
                return rowASNWifiAPReportRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                ASNWifiAPReportDataTable cln = ((ASNWifiAPReportDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new ASNWifiAPReportDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal void InitVars() {
                this.columnPurchasing_Document_Number = base.Columns["Purchasing_Document_Number"];
                this.columnEAN_Code_of_Device = base.Columns["EAN_Code_of_Device"];
                this.columnSerial_Number = base.Columns["Serial_Number"];
                this.columnPallet_Number = base.Columns["Pallet_Number"];
                this.columnMaster_Shipper_Number = base.Columns["Master_Shipper_Number"];
                this.columnVendor_Lot_Number = base.Columns["Vendor_Lot_Number"];
                this.columnInvoice_Number = base.Columns["Invoice_Number"];
                this.columnMonth_of_Manufacturing = base.Columns["Month_of_Manufacturing"];
                this.columnInvoice_Date = base.Columns["Invoice_Date"];
                this.columnWarranty_in_Days = base.Columns["Warranty_in_Days"];
                this.columnPhysical_Device_Model = base.Columns["Physical_Device_Model"];
                this.columnPhysical_Device_Type = base.Columns["Physical_Device_Type"];
                this.columnPhysical_Device_Vendor = base.Columns["Physical_Device_Vendor"];
                this.columnDevice_IMEI_number = base.Columns["Device_IMEI_number"];
                this.columnOUI = base.Columns["OUI"];
                this.columnSoftware_Version = base.Columns["Software_Version"];
                this.columnPre_Password = base.Columns["Pre_Password"];
                this.columnDevice_Status = base.Columns["Device_Status"];
                this.columnLogical_Function_Type = base.Columns["Logical_Function_Type"];
                this.columnDevice_Component = base.Columns["Device_Component"];
                this.columnBase_MAC_ID = base.Columns["Base_MAC_ID"];
                this.columnGlobal_SSID1 = base.Columns["Global_SSID1"];
                this.columnGlobal_SSID2 = base.Columns["Global_SSID2"];
                this.columnWPA_PSKSSID_PWD = base.Columns["WPA_PSKSSID_PWD"];
                this.columnGPON_ID = base.Columns["GPON_ID"];
                this.columnAction_for_Granite = base.Columns["Action_for_Granite"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            private void InitClass() {
                this.columnPurchasing_Document_Number = new global::System.Data.DataColumn("Purchasing_Document_Number", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPurchasing_Document_Number);
                this.columnEAN_Code_of_Device = new global::System.Data.DataColumn("EAN_Code_of_Device", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEAN_Code_of_Device);
                this.columnSerial_Number = new global::System.Data.DataColumn("Serial_Number", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSerial_Number);
                this.columnPallet_Number = new global::System.Data.DataColumn("Pallet_Number", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPallet_Number);
                this.columnMaster_Shipper_Number = new global::System.Data.DataColumn("Master_Shipper_Number", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMaster_Shipper_Number);
                this.columnVendor_Lot_Number = new global::System.Data.DataColumn("Vendor_Lot_Number", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVendor_Lot_Number);
                this.columnInvoice_Number = new global::System.Data.DataColumn("Invoice_Number", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInvoice_Number);
                this.columnMonth_of_Manufacturing = new global::System.Data.DataColumn("Month_of_Manufacturing", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMonth_of_Manufacturing);
                this.columnInvoice_Date = new global::System.Data.DataColumn("Invoice_Date", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInvoice_Date);
                this.columnWarranty_in_Days = new global::System.Data.DataColumn("Warranty_in_Days", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWarranty_in_Days);
                this.columnPhysical_Device_Model = new global::System.Data.DataColumn("Physical_Device_Model", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPhysical_Device_Model);
                this.columnPhysical_Device_Type = new global::System.Data.DataColumn("Physical_Device_Type", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPhysical_Device_Type);
                this.columnPhysical_Device_Vendor = new global::System.Data.DataColumn("Physical_Device_Vendor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPhysical_Device_Vendor);
                this.columnDevice_IMEI_number = new global::System.Data.DataColumn("Device_IMEI_number", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDevice_IMEI_number);
                this.columnOUI = new global::System.Data.DataColumn("OUI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOUI);
                this.columnSoftware_Version = new global::System.Data.DataColumn("Software_Version", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSoftware_Version);
                this.columnPre_Password = new global::System.Data.DataColumn("Pre_Password", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPre_Password);
                this.columnDevice_Status = new global::System.Data.DataColumn("Device_Status", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDevice_Status);
                this.columnLogical_Function_Type = new global::System.Data.DataColumn("Logical_Function_Type", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLogical_Function_Type);
                this.columnDevice_Component = new global::System.Data.DataColumn("Device_Component", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDevice_Component);
                this.columnBase_MAC_ID = new global::System.Data.DataColumn("Base_MAC_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBase_MAC_ID);
                this.columnGlobal_SSID1 = new global::System.Data.DataColumn("Global_SSID1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGlobal_SSID1);
                this.columnGlobal_SSID2 = new global::System.Data.DataColumn("Global_SSID2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGlobal_SSID2);
                this.columnWPA_PSKSSID_PWD = new global::System.Data.DataColumn("WPA_PSKSSID_PWD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWPA_PSKSSID_PWD);
                this.columnGPON_ID = new global::System.Data.DataColumn("GPON_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGPON_ID);
                this.columnAction_for_Granite = new global::System.Data.DataColumn("Action_for_Granite", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAction_for_Granite);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ASNWifiAPReportRow NewASNWifiAPReportRow() {
                return ((ASNWifiAPReportRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ASNWifiAPReportRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(ASNWifiAPReportRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ASNWifiAPReportRowChanged != null)) {
                    this.ASNWifiAPReportRowChanged(this, new ASNWifiAPReportRowChangeEvent(((ASNWifiAPReportRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ASNWifiAPReportRowChanging != null)) {
                    this.ASNWifiAPReportRowChanging(this, new ASNWifiAPReportRowChangeEvent(((ASNWifiAPReportRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ASNWifiAPReportRowDeleted != null)) {
                    this.ASNWifiAPReportRowDeleted(this, new ASNWifiAPReportRowChangeEvent(((ASNWifiAPReportRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ASNWifiAPReportRowDeleting != null)) {
                    this.ASNWifiAPReportRowDeleting(this, new ASNWifiAPReportRowChangeEvent(((ASNWifiAPReportRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void RemoveASNWifiAPReportRow(ASNWifiAPReportRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ASNWifiAPSAP_Report ds = new ASNWifiAPSAP_Report();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "ASNWifiAPReportDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ASNWifiAPReportRow : global::System.Data.DataRow {
            
            private ASNWifiAPReportDataTable tableASNWifiAPReport;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal ASNWifiAPReportRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableASNWifiAPReport = ((ASNWifiAPReportDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Purchasing_Document_Number {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Purchasing_Document_NumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Purchasing_Document_Number\' in table \'ASNWifiAPReport\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Purchasing_Document_NumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string EAN_Code_of_Device {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.EAN_Code_of_DeviceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EAN_Code_of_Device\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.EAN_Code_of_DeviceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Serial_Number {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Serial_NumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Serial_Number\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Serial_NumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Pallet_Number {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Pallet_NumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Pallet_Number\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Pallet_NumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Master_Shipper_Number {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Master_Shipper_NumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Master_Shipper_Number\' in table \'ASNWifiAPReport\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Master_Shipper_NumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Vendor_Lot_Number {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Vendor_Lot_NumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Vendor_Lot_Number\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Vendor_Lot_NumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Invoice_Number {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Invoice_NumberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Invoice_Number\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Invoice_NumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Month_of_Manufacturing {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Month_of_ManufacturingColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Month_of_Manufacturing\' in table \'ASNWifiAPReport\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Month_of_ManufacturingColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Invoice_Date {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Invoice_DateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Invoice_Date\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Invoice_DateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Warranty_in_Days {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Warranty_in_DaysColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Warranty_in_Days\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Warranty_in_DaysColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Physical_Device_Model {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Physical_Device_ModelColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Physical_Device_Model\' in table \'ASNWifiAPReport\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Physical_Device_ModelColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Physical_Device_Type {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Physical_Device_TypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Physical_Device_Type\' in table \'ASNWifiAPReport\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Physical_Device_TypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Physical_Device_Vendor {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Physical_Device_VendorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Physical_Device_Vendor\' in table \'ASNWifiAPReport\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Physical_Device_VendorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Device_IMEI_number {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Device_IMEI_numberColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Device_IMEI_number\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Device_IMEI_numberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string OUI {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.OUIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OUI\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.OUIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Software_Version {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Software_VersionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Software_Version\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Software_VersionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Pre_Password {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Pre_PasswordColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Pre_Password\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Pre_PasswordColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Device_Status {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Device_StatusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Device_Status\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Device_StatusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Logical_Function_Type {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Logical_Function_TypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Logical_Function_Type\' in table \'ASNWifiAPReport\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Logical_Function_TypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Device_Component {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Device_ComponentColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Device_Component\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Device_ComponentColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Base_MAC_ID {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Base_MAC_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Base_MAC_ID\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Base_MAC_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Global_SSID1 {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Global_SSID1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Global_SSID1\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Global_SSID1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Global_SSID2 {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Global_SSID2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Global_SSID2\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Global_SSID2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string WPA_PSKSSID_PWD {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.WPA_PSKSSID_PWDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'WPA_PSKSSID_PWD\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.WPA_PSKSSID_PWDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string GPON_ID {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.GPON_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GPON_ID\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.GPON_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Action_for_Granite {
                get {
                    try {
                        return ((string)(this[this.tableASNWifiAPReport.Action_for_GraniteColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Action_for_Granite\' in table \'ASNWifiAPReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableASNWifiAPReport.Action_for_GraniteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsPurchasing_Document_NumberNull() {
                return this.IsNull(this.tableASNWifiAPReport.Purchasing_Document_NumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetPurchasing_Document_NumberNull() {
                this[this.tableASNWifiAPReport.Purchasing_Document_NumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsEAN_Code_of_DeviceNull() {
                return this.IsNull(this.tableASNWifiAPReport.EAN_Code_of_DeviceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetEAN_Code_of_DeviceNull() {
                this[this.tableASNWifiAPReport.EAN_Code_of_DeviceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsSerial_NumberNull() {
                return this.IsNull(this.tableASNWifiAPReport.Serial_NumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetSerial_NumberNull() {
                this[this.tableASNWifiAPReport.Serial_NumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsPallet_NumberNull() {
                return this.IsNull(this.tableASNWifiAPReport.Pallet_NumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetPallet_NumberNull() {
                this[this.tableASNWifiAPReport.Pallet_NumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsMaster_Shipper_NumberNull() {
                return this.IsNull(this.tableASNWifiAPReport.Master_Shipper_NumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetMaster_Shipper_NumberNull() {
                this[this.tableASNWifiAPReport.Master_Shipper_NumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsVendor_Lot_NumberNull() {
                return this.IsNull(this.tableASNWifiAPReport.Vendor_Lot_NumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetVendor_Lot_NumberNull() {
                this[this.tableASNWifiAPReport.Vendor_Lot_NumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsInvoice_NumberNull() {
                return this.IsNull(this.tableASNWifiAPReport.Invoice_NumberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetInvoice_NumberNull() {
                this[this.tableASNWifiAPReport.Invoice_NumberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsMonth_of_ManufacturingNull() {
                return this.IsNull(this.tableASNWifiAPReport.Month_of_ManufacturingColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetMonth_of_ManufacturingNull() {
                this[this.tableASNWifiAPReport.Month_of_ManufacturingColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsInvoice_DateNull() {
                return this.IsNull(this.tableASNWifiAPReport.Invoice_DateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetInvoice_DateNull() {
                this[this.tableASNWifiAPReport.Invoice_DateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsWarranty_in_DaysNull() {
                return this.IsNull(this.tableASNWifiAPReport.Warranty_in_DaysColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetWarranty_in_DaysNull() {
                this[this.tableASNWifiAPReport.Warranty_in_DaysColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsPhysical_Device_ModelNull() {
                return this.IsNull(this.tableASNWifiAPReport.Physical_Device_ModelColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetPhysical_Device_ModelNull() {
                this[this.tableASNWifiAPReport.Physical_Device_ModelColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsPhysical_Device_TypeNull() {
                return this.IsNull(this.tableASNWifiAPReport.Physical_Device_TypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetPhysical_Device_TypeNull() {
                this[this.tableASNWifiAPReport.Physical_Device_TypeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsPhysical_Device_VendorNull() {
                return this.IsNull(this.tableASNWifiAPReport.Physical_Device_VendorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetPhysical_Device_VendorNull() {
                this[this.tableASNWifiAPReport.Physical_Device_VendorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsDevice_IMEI_numberNull() {
                return this.IsNull(this.tableASNWifiAPReport.Device_IMEI_numberColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetDevice_IMEI_numberNull() {
                this[this.tableASNWifiAPReport.Device_IMEI_numberColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsOUINull() {
                return this.IsNull(this.tableASNWifiAPReport.OUIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetOUINull() {
                this[this.tableASNWifiAPReport.OUIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsSoftware_VersionNull() {
                return this.IsNull(this.tableASNWifiAPReport.Software_VersionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetSoftware_VersionNull() {
                this[this.tableASNWifiAPReport.Software_VersionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsPre_PasswordNull() {
                return this.IsNull(this.tableASNWifiAPReport.Pre_PasswordColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetPre_PasswordNull() {
                this[this.tableASNWifiAPReport.Pre_PasswordColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsDevice_StatusNull() {
                return this.IsNull(this.tableASNWifiAPReport.Device_StatusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetDevice_StatusNull() {
                this[this.tableASNWifiAPReport.Device_StatusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsLogical_Function_TypeNull() {
                return this.IsNull(this.tableASNWifiAPReport.Logical_Function_TypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetLogical_Function_TypeNull() {
                this[this.tableASNWifiAPReport.Logical_Function_TypeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsDevice_ComponentNull() {
                return this.IsNull(this.tableASNWifiAPReport.Device_ComponentColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetDevice_ComponentNull() {
                this[this.tableASNWifiAPReport.Device_ComponentColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsBase_MAC_IDNull() {
                return this.IsNull(this.tableASNWifiAPReport.Base_MAC_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetBase_MAC_IDNull() {
                this[this.tableASNWifiAPReport.Base_MAC_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsGlobal_SSID1Null() {
                return this.IsNull(this.tableASNWifiAPReport.Global_SSID1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetGlobal_SSID1Null() {
                this[this.tableASNWifiAPReport.Global_SSID1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsGlobal_SSID2Null() {
                return this.IsNull(this.tableASNWifiAPReport.Global_SSID2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetGlobal_SSID2Null() {
                this[this.tableASNWifiAPReport.Global_SSID2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsWPA_PSKSSID_PWDNull() {
                return this.IsNull(this.tableASNWifiAPReport.WPA_PSKSSID_PWDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetWPA_PSKSSID_PWDNull() {
                this[this.tableASNWifiAPReport.WPA_PSKSSID_PWDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsGPON_IDNull() {
                return this.IsNull(this.tableASNWifiAPReport.GPON_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetGPON_IDNull() {
                this[this.tableASNWifiAPReport.GPON_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsAction_for_GraniteNull() {
                return this.IsNull(this.tableASNWifiAPReport.Action_for_GraniteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetAction_for_GraniteNull() {
                this[this.tableASNWifiAPReport.Action_for_GraniteColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public class ASNWifiAPReportRowChangeEvent : global::System.EventArgs {
            
            private ASNWifiAPReportRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ASNWifiAPReportRowChangeEvent(ASNWifiAPReportRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public ASNWifiAPReportRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591